// La API pública de @ewms/design-system, nombre por nombre. El barril reexporta con `export *` para
// que el bundle pode; esta lista impide que un `export` interno se vuelva público sin decidirlo.
// Ver vault: 02-Arquitectura/Anatomia del Workspace.md.
import assert from 'node:assert/strict';
import path from 'node:path';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

/** Los nombres que exporta un public-api.ts, resueltos por el compilador. */
function exportedNames(file) {
  const program = ts.createProgram([file], {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.Preserve,
    experimentalDecorators: true,
    skipLibCheck: true,
    noEmit: true,
  });
  const checker = program.getTypeChecker();
  const module = checker.getSymbolAtLocation(program.getSourceFile(file));
  return checker
    .getExportsOfModule(module)
    .map((symbol) => symbol.name)
    .sort();
}

const DESIGN_SYSTEM = [
  'ArrayTableSource',
  'Badge',
  'BadgeDescriptor',
  'BadgeDictionary',
  'Banner',
  'Breadcrumbs',
  'BulkActionEvent',
  'Button',
  'ButtonGround',
  'ButtonIconPosition',
  'ButtonSize',
  'ButtonVariant',
  'Card',
  'CardGroup',
  'CellContext',
  'CellTemplate',
  'Checkbox',
  'ColumnAction',
  'ConfirmOptions',
  'Crumb',
  'DESIGN_SYSTEM_VERSION',
  'DatePicker',
  'DatePickerMessages',
  'DatePickerMode',
  'DatePickerValue',
  'DateRange',
  'DetailTemplate',
  'DialogService',
  'DialogVariant',
  'EWMS_DATE_PICKER_MESSAGES',
  'EWMS_FAVORITES_STORE',
  'EWMS_FAVORITE_LABELS',
  'EWMS_FILTER_BAR_MESSAGES',
  'EWMS_FILTER_CHIPS_MESSAGES',
  'EWMS_FORM_MESSAGES',
  'EWMS_PAGINATION_MESSAGES',
  'EWMS_SEARCH_BOX_MESSAGES',
  'EWMS_SELECT_MESSAGES',
  'EWMS_SHORTCUT_HELP_MESSAGES',
  'EWMS_SHORTCUT_MAP',
  'EWMS_SPLIT_BUTTON_MESSAGES',
  'EWMS_TABLE_FORMATTERS',
  'EWMS_TABLE_MESSAGES',
  'EmptyState',
  'EmptyStateAction',
  'EmptyStateKind',
  'EmptyStateSize',
  'EmptyTemplate',
  'ExportRequest',
  'Favorite',
  'FavoriteLabelResolver',
  'FavoriteToggle',
  'Favorites',
  'FavoritesNav',
  'FavoritesStore',
  'FeedbackVariant',
  'FieldSize',
  'FieldState',
  'FilterBar',
  'FilterBarMessages',
  'FilterChipsMessages',
  'FilterField',
  'FilterFieldValue',
  'FilterValues',
  'FormAction',
  'FormErrorKind',
  'FormErrorWriter',
  'FormErrorWriters',
  'FormMessages',
  'FormPattern',
  'ICON_CATEGORIES',
  'Icon',
  'IconCategory',
  'IconName',
  'IconSize',
  'InMemoryFavoritesStore',
  'Input',
  'InputType',
  'KeyboardShortcuts',
  'MenuItem',
  'NavBottom',
  'NavItem',
  'NavRail',
  'NumberRange',
  'OpenDialogOptions',
  'Pagination',
  'PaginationMessages',
  'Radio',
  'RadioGroup',
  'RowActivateEvent',
  'RowMenuEvent',
  'RowState',
  'SCAN_MIN_KEYSTROKES',
  'SCAN_THRESHOLD_TOKEN',
  'SEARCH_PAGE_SIZE',
  'ScanDetector',
  'ScanVerdict',
  'SearchBox',
  'SearchBoxMessages',
  'SearchDisplay',
  'SearchPage',
  'SearchSource',
  'Select',
  'SelectMessages',
  'SelectOption',
  'SemanticFamily',
  'SetFilter',
  'ShortcutAction',
  'ShortcutBinding',
  'ShortcutEvent',
  'ShortcutHelpMessages',
  'ShortcutMap',
  'ShortcutOutcome',
  'ShortcutsHost',
  'SplitAction',
  'SplitButton',
  'SplitButtonMessages',
  'Tab',
  'Table',
  'TableAggregate',
  'TableChildren',
  'TableColumn',
  'TableColumnType',
  'TableColumnWidth',
  'TableDensity',
  'TableFilterValue',
  'TableFormatters',
  'TableMessages',
  'TablePage',
  'TablePin',
  'TableQuery',
  'TableSort',
  'TableSource',
  'TableView',
  'Tabs',
  'TabsMode',
  'Text',
  'TextVariant',
  'Toast',
  'ToastOutlet',
  'ToastService',
  'Toggle',
  'Tooltip',
  'TooltipPosition',
  'Unregister',
  'Viewport',
  'confirmDiscard',
  'isDateRange',
  'isNumberRange',
  'isSetFilter',
  'isSingleCharacter',
  'parentOf',
  'parseTableDate',
];

describe('the public API of @ewms/design-system', () => {
  it('exports exactly the agreed names: adding one is a decision, not a side effect', () => {
    const file = path.join(ROOT, 'projects/design-system/src/public-api.ts');
    assert.deepEqual(exportedNames(file), [...DESIGN_SYSTEM].sort());
  });
});
